### ISSUE TITLE
Is there a way to skip checks?

### ISSUE THREAD

**Issue by jacebrowning** [joshfriend/hooker#11]
Say I'm leaving for vacation and need to hand off my code in its current state. Is there a way to commit/push while ignoring failing checks?

**Comment by joshfriend** [comment]
Git lets you pass `--no-verify` flag, which makes it skip execution of any hooks.

**Comment by jacebrowning** [comment]
Cool! That might be worth documenting somewhere in the README.

**Comment by joshfriend** [comment]
Reopening so I remember to add that...
