### ISSUE TITLE
Check for "WIP" commits before pushing

### ISSUE THREAD

**Issue by joshfriend** [joshfriend/hooker#3]
Possibly offer a warning suggesting a rebase to squash such commits.

**Comment by jacebrowning** [comment]
I like it!

**Comment by joshfriend** [comment]
Could also check if previous commit was `WIP` and suggest `--amend`

**Comment by jacebrowning** [comment]
![xy](http://memegen.link/xy/teach-people/all-of-the-git.jpg)
